function matrix_DH = transform(r, alpha, d, teta)
    matrix_DH = [cos(teta) -sin(teta)*cos(alpha) sin(teta)*sin(alpha) r*cos(teta); ...
                 sin(teta) cos(teta)*cos(alpha) -cos(teta)*sin(alpha) r*sin(teta); ...
                 0 sin(alpha) cos(alpha) d; ...
                 0 0 0 1];
end

